### ISSUE TITLE
Getting the error ```TypeError: Cannot read properties of undefined (reading 'style')```

### ISSUE THREAD

**Issue by HuckToohey** [NexovaDev/UpdateHub#1092]
Getting the error ```TypeError: Cannot read properties of undefined (reading 'style')
    at C:\Users\null\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:799170
    at Object.bJlPO (C:\Users\null\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:135873)
    at Object.jYbkB (C:\Users\null\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:252499)
    at C:\Users\null\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:255941
    at Array.forEach (<anonymous>)
    at MutationObserver.<anonymous> (C:\Users\null\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:252777)```.

**Comment by HuckToohey** [comment]
This was the second error in a row upon first run, immediately following and displacing one which alerts me that its own widget dependency is out of date (this is on a new Windows11 Pro 22H2 machine with all current updates and patches) and instructing me to run a search on Windows Store (which I never use and would prefer not ever to have to do so) for software which is not found, there. Tried putting it in quotes. Find only hundreds of seemingly unrelated games and so so forth.

**Comment by HuckToohey** [comment]
WinGet is available here: [https://www.powershellgallery.com/packages/Microsoft.WinGet.Client/0.2.1](https://www.powershellgallery.com/packages/Microsoft.WinGet.Client/0.2.1)

**Comment by HuckToohey** [comment]
The Microsoft Store version of WinGet is actually called APK App Installer.
