### ISSUE TITLE
Getting the error ```Error: Timeout reached```

### ISSUE THREAD

**Issue by slord399** [NexovaDev/UpdateHub#1242]
Getting the error ```Error: Timeout reached
    at C:\Users\Tony_Lewis\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:1017884```.

[2/9/2024 2:19:56 AM]: Load event: apps.html (at preload.js:1:476882)
[2/9/2024 2:19:56 AM]: Testing internet speed, please wait... (at preload.js:1:808224)
[2/9/2024 2:19:57 AM]: Checking for updates... (at preload.js:1:1020311)
[2/9/2024 2:19:57 AM]: Internet speed is 44.59 Mbps (at preload.js:1:815685)
[2/9/2024 2:20:03 AM]: -1 Updates found (at preload.js:1:1041534)
[2/9/2024 2:20:04 AM]: Getting app data... (at preload.js:1:1046222)
[2/9/2024 2:21:37 AM]: Error: Timeout reached
    at C:\Users\Tony_Lewis\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:1017884 (at preload.js:1:1154221)
[2/9/2024 2:21:37 AM]: Failed to send error report (at preload.js:1:4759)

**Comment by slord399** [comment]
There is no app awaiting to get updated when I run winget from cmd so this is not ideal and info they say on log be wrong too.
