### ISSUE TITLE
Getting the error ```Error: Timeout reached```

### ISSUE THREAD

**Issue by alexACMA** [NexovaDev/UpdateHub#148]
Getting the error ```Error: Timeout reached
    at C:\Users\Laser_Avanz\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:808619```.

**Comment by vtzsolt** [comment]
Same error.
Unhandled Error
TypeError: Invalid badgeNumber specified.
Expected: number
Got: object
    at Badge.update (C:/Users/Zsolt/AppData/Local/Programs/update-hub/resources/app.asar/node_modules/electron-taskbar-badge/lib/cjs/index.js:66:10)
    at SystemPreferences.<anonymous> (C:/Users/Zsolt/AppData/Local/Programs/update-hub/resources/app.asar/node_modules/electron-taskbar-badge/lib/cjs/index.js:50:9)
    at SystemPreferences.emit (node:events:513:28)
Unhandled Promise Rejection
Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at node:electron/js2c/renderer_init:2:16972
    at EventEmitter.<anonymous> (node:electron/js2c/renderer_init:2:11161)
    at EventEmitter.emit (node:events:513:28)
    at Object.onMessage (node:electron/js2c/renderer_init:2:9264)

**Comment by KK-Designs** [comment]
> Same error. Unhandled Error TypeError: Invalid badgeNumber specified. Expected: number Got: object at Badge.update (C:/Users/Zsolt/AppData/Local/Programs/update-hub/resources/app.asar/node_modules/electron-taskbar-badge/lib/cjs/index.js:66:10) at SystemPreferences. (C:/Users/Zsolt/AppData/Local/Programs/update-hub/resources/app.asar/node_modules/electron-taskbar-badge/lib/cjs/index.js:50:9) at SystemPreferences.emit (node:events:513:28) Unhandled Promise Rejection Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error. at node:electron/js2c/renderer_init:2:16972 at EventEmitter. (node:electron/js2c/renderer_init:2:11161) at EventEmitter.emit (node:events:513:28) at Object.onMessage (node:electron/js2c/renderer_init:2:9264)

This issue was fixed in the latest release. Update and try again
