### ISSUE TITLE
Getting the error ```TypeError: Cannot convert undefined or null to object```

### ISSUE THREAD

**Issue by tracit99** [NexovaDev/UpdateHub#1728]
Getting the error ```TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at _0x79d81a.oninput (C:\Users\RMT\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:582899)
    at _0x305904.<computed> (C:\Users\RMT\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:932509)```.

**Comment by tracit99** [comment]
I Ignored five Windows and Microsoft updates because they could not be updated by UpdateHub.
