### ISSUE TITLE
Getting the error ```TypeError: Cannot read properties of undefined (reading 'replace')```

### ISSUE THREAD

**Issue by keith-collyer** [NexovaDev/UpdateHub#193]
Getting the error ```TypeError: Cannot read properties of undefined (reading 'replace')
    at escapeRegExp (C:\Users\keith\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:122617)
    at C:\Users\keith\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:589408
    at Array.filter (<anonymous>)
    at FSWatcher.<anonymous> (C:\Users\keith\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:589385)
    at FSWatcher.emit (node:events:513:28)
    at FSWatcher._handle.onchange (node:internal/fs/watchers:215:12)```.

**Comment by KK-Designs** [comment]
What are you doing thats causing this issue?

**Comment by keith-collyer** [comment]
I honestly cannot recall, sorry

**Comment by KK-Designs** [comment]
The error doesn't repeatedly happen though correct?

**Comment by keith-collyer** [comment]
I've only seen it once

**Comment by KK-Designs** [comment]
Should be fixed since [v2.2.3](https://github.com/NexovaDev/UpdateHub/releases/tag/v2.2.3)
