### ISSUE TITLE
Getting the error ```TypeError: Cannot read properties of undefined (reading 'style')```

### ISSUE THREAD

**Issue by city2026** [NexovaDev/UpdateHub#2166]
Getting the error ```TypeError: Cannot read properties of undefined (reading 'style')
    at C:\Users\%user%\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:850668
    at Object.IFlyh (C:\Users\%user%\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:128409)
    at Object.TfMWV (C:\Users\%user%\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:236258)
    at Object.wPjMG (C:\Users\%user%\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:237464)
    at C:\Users\%user%\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:238293
    at Array.forEach (<anonymous>)
    at MutationObserver.<anonymous> (C:\Users\%user%\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:237651)```.

**Comment by city2026** [comment]
just uploaded a bug, didn't intended, but the program wanted me to. :)
don't care.
