### ISSUE TITLE
Getting the error ```TypeError: Cannot convert undefined or null to object```

### ISSUE THREAD

**Issue by gsd4me** [NexovaDev/UpdateHub#2201]
Getting the error ```TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at _0x539527.<computed> (C:\Users\Alan\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:740625)
    at _0x14d96e.<computed> (C:\Users\Alan\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:926990)```.

**Comment by gsd4me** [comment]
Got this error running the utility. Hope someone can make sense of it
