### ISSUE TITLE
Getting the error ```TypeError: Cannot read properties of undefined (reading 'replace')```

### ISSUE THREAD

**Issue by Corsair-63** [NexovaDev/UpdateHub#247]
Getting the error ```TypeError: Cannot read properties of undefined (reading 'replace')
    at escapeRegExp (C:\Users\corsa\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:125262)
    at C:\Users\corsa\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:589106
    at Array.filter (<anonymous>)
    at FSWatcher.<anonymous> (C:\Users\corsa\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:589083)
    at FSWatcher.emit (node:events:513:28)
    at FSEvent.onchange (node:internal/fs/watchers:215:12)```.

**Comment by KK-Designs** [comment]
What were you doing thats causing this issue?

**Comment by Corsair-63** [comment]
Not clear, after running for some hours, I have two computer connected by one KVM.

after some hours working, I exchanged to the other computer and I have such error in the screen.

**Comment by KK-Designs** [comment]
Should be fixed in the latest release 👍
