### ISSUE TITLE
Getting the error ```Error: Timeout reached```

### ISSUE THREAD

**Issue by Mirkuzzo** [NexovaDev/UpdateHub#261]
Getting the error ```Error: Timeout reached
    at C:\Users\mirko\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:816011```.

**Comment by Mirkuzzo** [comment]
After updating to the new version it doesn't update my applications

**Comment by KK-Designs** [comment]
What do you mean? Does it give an error message?

**Comment by slycordinator** [comment]
> What do you mean? Does it give an error message?

The error message is "Error: Timeout reached at C:\Users\[username]\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:816011."

It happens sporadically.
