### ISSUE TITLE
Getting the error ```Error: Timeout reached```

### ISSUE THREAD

**Issue by ted1958** [NexovaDev/UpdateHub#306]
Getting the error ```Error: Timeout reached
    at C:\Users\Thierry\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:818526```.

**Comment by DrHurt** [comment]
Same here sadly:
Error: Error: Timeout reached at C:\Users\User\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:818526
