### ISSUE TITLE
安裝后運行報錯，內容如下

### ISSUE THREAD

**Issue by streamgo** [NexovaDev/UpdateHub#8]
```
Error: Command failed: "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -Command "Get-ItemProperty -Path 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Accent' | Select-Object AccentPalette | ConvertTo-Json"
Get-ItemProperty : �޷�����Get-ItemProperty����ʶ��Ϊ cmdlet���������ű��ļ�������г�������ơ��������Ƶ�ƴд���������·
������ȷ��·����ȷ��Ȼ������һ�Ρ�
����λ�� ��:1 �ַ�: 1
+ Get-ItemProperty -Path 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersi ...
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-ItemProperty:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 

    at checkExecSyncError (node:child_process:911:11)
    at Object.execSync (node:child_process:983:15)
    at Object.execSync (node:electron/js2c/asar_bundle:2:12711)
    at getLightAccentColor (C:\Users\Administrator\AppData\Local\Programs\update-hub\resources\app.asar\node_modules\electron-taskbar-badge\lib\cjs\index.js:109:62)
    at new Badge (C:\Users\Administrator\AppData\Local\Programs\update-hub\resources\app.asar\node_modules\electron-taskbar-badge\lib\cjs\index.js:45:23)
    at createWindow (C:\Users\Administrator\AppData\Local\Programs\update-hub\resources\app.asar\app.js:1:5898)
    at C:\Users\Administrator\AppData\Local\Programs\update-hub\resources\app.asar\app.js:1:9367
```

---

update-hub 2.0.0
Electron 25.3.0
win32 10.0.19042
Locale: en-US

**Comment by KK-Designs** [comment]
We are working on a fix for this issue.

**Comment by KK-Designs** [comment]
Should've been fixed a while back, sorry for not notifying
